disabled_rules:
  - valid_docs

opt_in_rules:
  - empty_count
  - force_unwrapping

included:
  - Peloton-UIColors
  - Example

excluded:
  - Example/Pods
  - Pods

line_length: 200

function_body_length:
  warning: 50
